### PR TITLE
added 6 job board links for worldwide

### PR DESCRIPTION
**Pull request by mastercodemarshal**

### CODE REVIEW

**Review by waitingwittykitty — COMMENTED** [review]
@mastercodemarshal , could you please resolve the conflicts?
Also, need to change the labels and project status.

**Comment by mastercodemarshal** [comment]
Hi @waitingwittykitty. I just resolved the conflicts.

And I will change the labels and project status after finishing the work.

**Review by waitingwittykitty — CHANGES_REQUESTED** [review]
Please remove bars in the line-ending

**Comment by mastercodemarshal** [comment]
I removed unnecessary bars. PTAL

**Review by waitingwittykitty — APPROVED** [review]

**Pull request merged**
